/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryUpdateName } from './categoryUpdateName';
import type { CategoryUpdateImageId } from './categoryUpdateImageId';

export interface CategoryUpdate {
  name?: CategoryUpdateName;
  imageId?: CategoryUpdateImageId;
}
