/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin and login API
 * OpenAPI spec version: 0.1.0
 */
import type { CategoryOut } from './categoryOut';
import type { Meta } from './meta';

export interface CategoriesListResponse {
  items: CategoryOut[];
  meta: Meta;
}
