/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { DefinitionOutCategory } from './definitionOutCategory';
import type { DefinitionOutLevel } from './definitionOutLevel';
import type { MeaningOut } from './meaningOut';

export interface DefinitionOut {
  id: number;
  text: string;
  category?: DefinitionOutCategory;
  level?: DefinitionOutLevel;
  meanings?: MeaningOut[];
}
