/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin and login API
 * OpenAPI spec version: 0.1.0
 */
import type { DefinitionOutIdsCategoryId } from './definitionOutIdsCategoryId';
import type { DefinitionOutIdsLevelId } from './definitionOutIdsLevelId';

export interface DefinitionOutIds {
  id: number;
  text: string;
  categoryId?: DefinitionOutIdsCategoryId;
  levelId?: DefinitionOutIdsLevelId;
  meaningIds?: number[];
}
