/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { DefinitionCreateCategoryId } from './definitionCreateCategoryId';
import type { DefinitionCreateLevelId } from './definitionCreateLevelId';

export interface DefinitionCreate {
  text: string;
  categoryId?: DefinitionCreateCategoryId;
  levelId?: DefinitionCreateLevelId;
  meaningIds?: number[];
}
