/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { DefinitionUpdateText } from './definitionUpdateText';
import type { DefinitionUpdateCategoryId } from './definitionUpdateCategoryId';
import type { DefinitionUpdateLevelId } from './definitionUpdateLevelId';
import type { DefinitionUpdateMeaningIds } from './definitionUpdateMeaningIds';

export interface DefinitionUpdate {
  text?: DefinitionUpdateText;
  categoryId?: DefinitionUpdateCategoryId;
  levelId?: DefinitionUpdateLevelId;
  meaningIds?: DefinitionUpdateMeaningIds;
}
