/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Learn language project
 * OpenAPI spec version: 0.1.0
 */

export type DeleteMeaningEndpointApiV1MeaningsMeaningIdDelete200 = { [key: string]: unknown };
