/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { ImageDefinitionCreateCategoryId } from './imageDefinitionCreateCategoryId';
import type { ImageDefinitionCreateLevelId } from './imageDefinitionCreateLevelId';

export interface ImageDefinitionCreate {
  imageId: number;
  categoryId?: ImageDefinitionCreateCategoryId;
  levelId?: ImageDefinitionCreateLevelId;
  meaningIds?: number[];
}
