/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { AssetOut } from './assetOut';
import type { ImageDefinitionOutCategoryId } from './imageDefinitionOutCategoryId';
import type { ImageDefinitionOutLevelId } from './imageDefinitionOutLevelId';
import type { ImageDefinitionOutCategory } from './imageDefinitionOutCategory';
import type { ImageDefinitionOutLevel } from './imageDefinitionOutLevel';
import type { MeaningOut } from './meaningOut';

export interface ImageDefinitionOut {
  id: number;
  imageId: number;
  image: AssetOut;
  categoryId?: ImageDefinitionOutCategoryId;
  levelId?: ImageDefinitionOutLevelId;
  meaningIds?: number[];
  type?: 'image';
  category?: ImageDefinitionOutCategory;
  level?: ImageDefinitionOutLevel;
  meanings?: MeaningOut[];
}
