/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { ImageDefinitionOut } from './imageDefinitionOut';
import type { Meta } from './meta';

export interface ImageDefinitionListResponse {
  items: ImageDefinitionOut[];
  meta: Meta;
}
