/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { ImageDefinitionUpdateImageId } from './imageDefinitionUpdateImageId';
import type { ImageDefinitionUpdateCategoryId } from './imageDefinitionUpdateCategoryId';
import type { ImageDefinitionUpdateLevelId } from './imageDefinitionUpdateLevelId';
import type { ImageDefinitionUpdateMeaningIds } from './imageDefinitionUpdateMeaningIds';

export interface ImageDefinitionUpdate {
  imageId?: ImageDefinitionUpdateImageId;
  categoryId?: ImageDefinitionUpdateCategoryId;
  levelId?: ImageDefinitionUpdateLevelId;
  meaningIds?: ImageDefinitionUpdateMeaningIds;
}
