/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */

export interface ImageAssetUploadOut {
  uploadUrl: string;
  fileKey: string;
  imageId: number;
}
