/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { IssueOut } from './issueOut';
import type { Meta } from './meta';

export interface IssuesListResponse {
  items: IssueOut[];
  meta: Meta;
}
