/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { IssueUpdateDecision } from './issueUpdateDecision';
import type { IssueUpdateStatusId } from './issueUpdateStatusId';

export interface IssueUpdate {
  decision?: IssueUpdateDecision;
  statusId?: IssueUpdateStatusId;
}
