/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { IssueOutText } from './issueOutText';
import type { IssueOutDecision } from './issueOutDecision';
import type { IssueOutReporter } from './issueOutReporter';
import type { IssueOutStatus } from './issueOutStatus';
import type { IssueOutType } from './issueOutType';
import type { IssueOutQuestion } from './issueOutQuestion';

export interface IssueOut {
  id: number;
  text?: IssueOutText;
  decision?: IssueOutDecision;
  reporter?: IssueOutReporter;
  status?: IssueOutStatus;
  type?: IssueOutType;
  question?: IssueOutQuestion;
  meaning: string;
  definitions: string[];
  createdAt: string;
  updatedAt: string;
}
