/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */

export interface LevelCreate {
  name: string;
  alias: string;
  questionTypeIds: number[];
}
