/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { MeaningUpdateName } from './meaningUpdateName';
import type { MeaningUpdateCategoryId } from './meaningUpdateCategoryId';
import type { MeaningUpdateLevelId } from './meaningUpdateLevelId';

export interface MeaningUpdate {
  name?: MeaningUpdateName;
  categoryId?: MeaningUpdateCategoryId;
  levelId?: MeaningUpdateLevelId;
}
