/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin and login API
 * OpenAPI spec version: 0.1.0
 */
import type { MeaningCreateCategoryId } from './meaningCreateCategoryId';
import type { MeaningCreateLevelId } from './meaningCreateLevelId';

export interface MeaningCreate {
  name: string;
  categoryId?: MeaningCreateCategoryId;
  levelId?: MeaningCreateLevelId;
}
