/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin and login API
 * OpenAPI spec version: 0.1.0
 */
import type { MeaningOutCategory } from './meaningOutCategory';
import type { MeaningOutLevel } from './meaningOutLevel';

export interface MeaningOut {
  id: number;
  name: string;
  category?: MeaningOutCategory;
  level?: MeaningOutLevel;
}
