/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { MeaningOut } from './meaningOut';
import type { Meta } from './meta';

export interface MeaningsListResponse {
  /**
   * Список категорий
   * @minItems 0
   * @maxItems 100
   */
  items: MeaningOut[];
  meta: Meta;
}
