/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin and login API
 * OpenAPI spec version: 0.1.0
 */

export interface Meta {
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  totalCount: number;
}
