/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionTypeName } from './questionTypeName';
import type { CategoryOut } from './categoryOut';
import type { LevelOut } from './levelOut';

export interface QuestionOut {
  type: QuestionTypeName;
  category: CategoryOut;
  level: LevelOut;
}
