/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { QuestionTypeOut } from './questionTypeOut';

export interface QuestionTypeListResponse {
  items: QuestionTypeOut[];
}
