/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Learn language project
 * OpenAPI spec version: 0.1.0
 */

export type ReadDefinitionsApiV1DefinitionsGetParams = {
/**
 * offset
 */
offset?: number;
/**
 * page size
 */
limit?: number;
/**
 * Search query
 */
q?: string;
};
