/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { TextDefinitionOutIdsAudioId } from './textDefinitionOutIdsAudioId';
import type { TextDefinitionOutIdsCategoryId } from './textDefinitionOutIdsCategoryId';
import type { TextDefinitionOutIdsLevelId } from './textDefinitionOutIdsLevelId';

export interface TextDefinitionOutIds {
  id: number;
  text: string;
  type?: 'text';
  audioId?: TextDefinitionOutIdsAudioId;
  categoryId?: TextDefinitionOutIdsCategoryId;
  levelId?: TextDefinitionOutIdsLevelId;
  meaningIds?: number[];
}
