/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { TextDefinitionCreateCategoryId } from './textDefinitionCreateCategoryId';
import type { TextDefinitionCreateLevelId } from './textDefinitionCreateLevelId';

export interface TextDefinitionCreate {
  text: string;
  categoryId?: TextDefinitionCreateCategoryId;
  levelId?: TextDefinitionCreateLevelId;
  meaningIds?: number[];
}
