/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { TextDefinitionOut } from './textDefinitionOut';
import type { Meta } from './meta';

export interface TextDefinitionListResponse {
  items: TextDefinitionOut[];
  meta: Meta;
}
