/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin and login API
 * OpenAPI spec version: 0.1.0
 */
import type { UserOutName } from './userOutName';

export interface UserOut {
  /**
   * @minimum 0
   * @maximum 9007199254740991
   */
  id: number;
  email: string;
  name?: UserOutName;
}
