/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * admin
 * OpenAPI spec version: 0.1.0
 */
import type { UserOut } from './userOut';
import type { Meta } from './meta';

export interface UsersListResponse {
  items: UserOut[];
  meta: Meta;
}
