/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * auth API
 * OpenAPI spec version: 0.1.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export const getAuthAPI = () => {
/**
 * @summary Login
 */
const loginGoogleLoginGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/google/login`,options
    );
  }

/**
 * @summary Auth Callback
 */
const authCallbackGoogleCallbackGet = <TData = AxiosResponse<unknown>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/google/callback`,options
    );
  }

return {loginGoogleLoginGet,authCallbackGoogleCallbackGet}};
export type LoginGoogleLoginGetResult = AxiosResponse<unknown>
export type AuthCallbackGoogleCallbackGetResult = AxiosResponse<unknown>
